name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run unit tests
      run: |
        echo "Running tests..."
        # Di sini misalnya nanti kamu mau tambah unittest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/
          rm -rf ecommerce-cc
          git clone https://github.com/DavneyRestraDanaz/ecommerce-cc.git
          cd ecommerce-cc
          pip3 install -r requirements.txt
          sudo pkill -f app.py || true
          nohup python3 app.py &